name: Content Quality Check

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop]

jobs:
  quality-check:
    name: Documentation Quality Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Run Astro type and content checks
        run: pnpm astro check
        
      - name: Run spell check
        run: pnpm spell:check
        
      - name: Build documentation
        run: pnpm build
        
      - name: Test build output
        run: |
          if [ ! -d "dist" ]; then
            echo "❌ Build failed - no dist directory found"
            exit 1
          fi
          
          if [ ! -f "dist/index.html" ]; then
            echo "❌ Build failed - no index.html found"
            exit 1
          fi
          
          echo "✅ Build successful - documentation ready for deployment"
